spring:
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: trace
